//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.28 at 09:11:22 PM WEST 
//


package com.ensa.ebanking.solde;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="fistName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fistName"
})
@XmlRootElement(name = "ConsultationSoldeRequest")
public class ConsultationSoldeRequest {

    @XmlElement(required = true)
    protected String fistName;

    /**
     * Gets the value of the fistName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFistName() {
        return fistName;
    }

    /**
     * Sets the value of the fistName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFistName(String value) {
        this.fistName = value;
    }

}
